name: Create Yearly Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming yearly release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_python-create-version-branch.yml@fbf1e4db594578f8ea0c95ac8561cecb3c7a96c2
    secrets:
      VALKYRJA_GHA_APP_ID: ${{ secrets.VALKYRJA_GHA_APP_ID }}
      VALKYRJA_GHA_PRIVATE_KEY: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}
    with:
      dependencies: |
        [
          {"name": "Ruff",           "directory": ".github/ci/ruff"},
          {"name": "mypy",           "directory": ".github/ci/mypy"},
          {"name": "Bandit",         "directory": ".github/ci/bandit"},
          {"name": "import-linter",  "directory": ".github/ci/importlinter"},
          {"name": "pytest",         "directory": ".github/ci/pytest"}
        ]
